name: Semgrep
on:
  pull_request: {}
  push:
    branches: ["*", "!main"]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Scan
        run: semgrep scan -f rules -l go --json --output=semgrep.json
      - name: Upload Report
        uses: actions/upload-artifact@v2
        with:
          name: semgrep-report
          path: semgrep.json

  report:
    name: Generate Report
    needs: semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Download Report
        uses: actions/download-artifact@v2
        with:
          name: semgrep-report
      - name: Process Report
        uses: hoeg/semgrep-report@v1.0.0
        with:
          github_secret: ${{secrets.GITHUB_TOKEN}}
          report_path: semgrep.json
